version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - ./elasticsearch/es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticserach.yml:/usr/share/elasticsearch/config/elasticserach.yml
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./log:/var/log/logstash/input
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk

networks:
  elk:
